name: "CI: App"
description:
  "Run tests and checks on the application code. Should be run when any code changes are merged,
  excluding infrastructure and documentation changes."

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main, develop]
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.scss"
      - "**.js"
      - "**.mjs"
      - "**.css"
      - "**.json"
      - "**.yml"
  workflow_dispatch:

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/ampdresume?schema=ampdresume
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  NEXT_PUBLIC_ENVIRONMENT_NAME: ci
  NEXT_PUBLIC_BASE_URL: http://localhost:3000

jobs:
  code-tests:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-dependencies

      - name: Check formatting
        run: npm run prettier

      - name: Check lint
        run: npm run lint

      - name: Check types
        run: npm run types:check

      - name: Run tests
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
